name: Deploy Phil's python env to Amazon ECR

on:
  push:
    branches:
      - prod
    paths:
      - "builds/ibdgc-db-env/v1/**"

env:
  AWS_REGION: us-east-1 # set this to your preferred AWS region, e.g. us-west-1
  REGISTRY_ALIAS: chobiolab # aws ecr public alias
  VER: # version of coreSC
  REPOSITORY: ibdgc-db-env # aws ecr repo path
  BUILD_PATH: builds/ibdgc-db-env/v1 # dir location of build files in repo

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      # added this line to shorten the SHA tag
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-7`" >> $GITHUB_ENV

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Clone Private Repo
        uses: actions/checkout@v3
        with:
          repository: git@github.com:ibdgc/ibdgc-db.git
          ref: pschumm/reporting
          path: $BUILD_PATH/ibdgc-db

      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        run: |
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:v1 $BUILD_PATH
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:v1
